#!/bin/sh
portals="xdg-desktop-portal-gtk xdg-desktop-portal-hyprland xdg-desktop-portal"

exitHyprland () {
        hyprctl dispatch exit
}

stopXDGP () {
        for portal in $portals; do
                systemctl --user stop "$portal"
        done
}

checkXDGP () {
        while :; do
                all_inactive=1
                for portal in $portals; do
                        status=$(systemctl --user is-active "$portal" 2>/dev/null)
                        printf 'DEBUG: %s -> %s\n' "$portal" "$status" >&2
                        if [ "$status" = "active" ]; then
                               all_inactive=0
                                break
                        fi
                done

                [ "$all_inactive" -eq 1 ] && return 0
                sleep 3
        done
}

main () {
        stopXDGP
        checkXDGP
        exitHyprland
}

main
