#!/bin/sh
#
# summary: a simple posix script for bringing dmenu_run functionality to fzf
# repository: https://github.com/hollowillow/scripts
#
# usage: fmenu

if [ "$1" = "-h" ]; then
        sed "1,2d;s/^# //;s/^#$/ /;/^$/ q" "$0"; exit 0
fi

for DIR in $(echo "$PATH" | tr ':' ' '); do
    ls "$DIR"
done | sort -u | fzf | while read -r CMD; do
        nohup sh -c "$CMD" >/dev/null 2>&1 &
done
