#!/bin/sh
#
# script: fzgrep
# description: a simple, extensible, POSIX compliant fuzzy grep searching shell script
# dependencies: fzf, bat(can be changed to cat but looses syntax highlighting), ripgrep, vim/nvim(make sure you have $EDITOR set)
# github: https://github.com/hollowillow/scripts
#
# DEFAULT KEYMAPS
# enter: open $EDITOR on line and column of query
# ctrl-o: open $EDITOR on line and column of query, keeps fzf open in background
# tab: select
# ctrl-a: select all
# ctrl-d: unselect all
# ctrl-t: toggle preview window
#

if [ "$*" = '-h' ]; then

printf "fzgrep is a simple, extensible, POSIX compliant fuzzy grep searching shell script
Github: https://github.com/hollowillow/scripts\n 
\tUsage: fzgrep [options] [arguments]\n 
OPTIONS\n 
\t-h\tDisplay this help message\n
EXAMPLES\n
\tfzgrep\t\t\tOpens up fzf and let's you grep search through any files in current directory
\tfzgrep string\t\tUses the 'string' argument as the initial fzf query\n \n";
exit 0;

else

# fzf variables: {1} = filename, {2} = line, {3} = column, {4} = line contents
PREVIEW='bat --style=full --color=always --theme=ansi --highlight-line {2} {1}'
RELOAD='reload:rg --vimgrep --color=always --smart-case {q} || :'
# your $EDITOR might not work if it isn't vim/nvim, as this uses specific vim/nvim options by default
OPEN='if [ $FZF_SELECT_COUNT -eq 0 ]; then "$EDITOR" "+call cursor({2},{3})" {1}; else "$EDITOR" +cw -q {+f}; fi'

fzf \
        --disabled --multi --delimiter=":" \
        --ansi --color=16 \
        --bind "start:$RELOAD" --bind "change:$RELOAD" \
        --bind "enter:become:$OPEN" --bind "ctrl-o:execute:$OPEN" \
        --bind 'ctrl-a:select-all,ctrl-d:deselect-all,ctrl-t:toggle-preview' \
        --preview="$PREVIEW" --preview-label="[file preview]"\
        --with-nth="1,4" \
        --query="$*"

fi;
