#!/bin/sh
#
# summary: a simple posix script for powering down your system
# repository: http://github.com/hollowillow/scripts
#
# usage: power
#
# depedencies: systemctl, exit-hyprland (optional script for log out)

# creates a help message from comment block at the head of file
printHelp() { sed "1,2d;s/^# //;s/^#$/ /;/^$/ q" "$0"; exit 0; }
{ [ "$1" = "-h" ] || [ "$1" = "--help" ]; } && printHelp

printErr() { printf "%s$(basename "$0"): Error: $1\n" >&2; exit 1; }
command -v systemctl >/dev/null || printErr "dependency not found: systemctl"


main() {
        # items will be presented in the order they appear here
        OPTIONS="Power Off\nReboot\nSuspend\nHibernate\nLog Out\n"
        SELECTED="$(printf "$OPTIONS" | fzf --prompt 'power: ')"
        [ -z "$SELECTED" ] && exit 0

        # confirm selected invocation can be removed to skip confirmation per option
        confirmSelection() { printf 'Yes\nNo' | fzf --prompt='confirm: '; }
        case "$SELECTED" in
                "Power Off") [ "$(confirmSelection)" = "Yes" ] && systemctl poweroff;;
                "Reboot") [ "$(confirmSelection)" = "Yes" ] && systemctl reboot;;
                "Suspend") [ "$(confirmSelection)" = "Yes" ] && systemctl suspend;;
                "Hiberate") [ "$(confirmSelection)" = "Yes" ] && systemctl hibernate;;
                "Log Out") [ "$(confirmSelection)" = "Yes" ] && exit-hyprland;;
        esac
}

main
