#!/bin/sh
#
# summary: a simple posix script for powering down your system
# repository: http://github.com/hollowillow/scripts
#
# usage: power
#
# depedencies: systemctl, exit-hyprland (optional script for log out)

. _lib # library script with common functions and variables
case "$1" in -h|-help|--help|help) printHelp ;; esac
checkDependency "systemctl"

HIBERNATE="󰒲 Hibernate"
LOCK=" Lock"
LOGOUT="󰍂 Log Out"
POWER="⏻ Power Off"
REBOOT=" Reboot"
SUSPEND=" Suspend"

# set your prefered ordering
OPTIONS="$LOCK\n$POWER\n$REBOOT\n$HIBERNATE\n$SUSPEND\n$LOGOUT"

main() {
    SELECT=$(printf '%b' "$OPTIONS" | rofi -dmenu -theme ~/.config/rofi/themes/small.rasi)
    [ -n "$SELECT" ] || return
    [ "$(confirmSelection)" = "$YES" ] || return

    case "$SELECT" in
        "$HIBERNATE") systemctl hibernate;;
        "$LOCK") loginctl lock-session;;
        "$LOGOUT") exit-hyprland;;
        "$POWER") systemctl poweroff;;
        "$REBOOT") systemctl reboot;;
        "$SUSPEND") systemctl suspend;;
    esac
}

main
