#!/bin/sh

while getopts "b:" OPT
do
        case $OPT in
                b) case $OPTARG in
                        tab) BROWSER="$BROWSER --new-tab";;
                        window) BROWSER="$BROWSER --new-window";;
                        *) printf '%s\n' "Error: Incorrect argument" && exit 1;;
                   esac;;
                *) printf '%s\n' "Error: Incorrect option" && exit 1;;
        esac
done

CHOICES="DuckDuckGo\nGoogle\nArch Wiki\nGentoo Wiki\nYouTube\nGitHub\nDriveThruRPG\nNixOS package\nNixOS option\nProtonDB\nSteamDB"
CHOSEN=$(printf "$CHOICES" | $GUI_MENU 'engine: ')

if [ -z "$CHOSEN" ]; then printf '%s\n' "No engine chosen" && exit 0; fi

case "$CHOSEN" in
        "DuckDuckGo") ENGINE="duckduckgo.com/&q=" ;;
        "Google") ENGINE="google.com/search?q=";;
        "Arch Wiki") ENGINE="wiki.archlinux.org/index.php?search=";;
        "Gentoo Wiki") ENGINE="wiki.gentoo.org/index.php?title=search&search=";;
        "YouTube") ENGINE="youtube.com/results?search_query=";;
        "GitHub") ENGINE="github.com/search?q=";;
        "DriveThruRPG") ENGINE="drivethrurpg.com/en/browse?keyword=";;
        # using unstable channel by default, 
        "NixOS package") ENGINE="search.nixos.org/packages?channel=unstable&size=50&sort=relevance&query=";;
        "NixOS option") ENGINE="search.nixos.org/options?channel=unstable&size=50&sort=relevance&query=test";;
        "ProtonDB") ENGINE="www.protondb.com/search?q=";;
        "SteamDB") ENGINE="steamdb.info/search/?a=all&q=";;
esac

if [ -z "$ENGINE" ]; then 
        exit 1;
fi

QUERY="$(printf '' | $GUI_MENU 'query: ')"

if [ -z "$QUERY" ]; then
        exit 1;
fi

$BROWSER https://"${ENGINE}${QUERY}" &
