#!/bin/sh
#
# summary: a simple wrapper script for a pop up terminal
# repository: https://github.com/hollowillow/scripts
#
# usage: term-menu arg
# description: spawn any command in a toggleable terminal with the class script.term_menu

. _lib # library script with common functions and variables
case "$1" in -h|-help|--help|help) printHelp ;; esac
PID_FILE="/tmp/term-menu.pid"

[ -z "$TERMINAL" ] && printErr \
    "variable not set: TERMINAL" \
    "set your desired terminal for this script by setting a TERMINAL env variable"

[ -z "$*" ] && printErr \
    "no argument" \
    "try running 'term-menu help'"

[ -f "$PID_FILE" ] &&
    kill "$(cat "$PID_FILE")" 2>/dev/null &&
    rm "$PID_FILE" &&
    exit 0

"$TERMINAL" --class='script.term_menu' -e "$@" >/dev/null 2>&1 &
printf '%s' "$!" >"$PID_FILE" && exit 0
