#!/bin/sh
#
# description: simple posix wallpaper script for the wayland protocol
# dependencies: swaybg
# github: https://github.com/hollowillow/scripts
#
# usage: wallpaper [command]
# commands:
#       random
#       select
#
# exit 0 - script run succesfully
# exit 1 - no selection
# exit 2 - undefined variable
#

### define functions ###

randomWall () {
        WALLPAPER=$(find "$WALLPAPERS_DIR" -type f | shuf -n 1)
        swaybg --image "$WALLPAPER" &
        exit 0
}

selectWall () {
        WALLPAPER=$(find "$WALLPAPERS_DIR" -type f | rev | cut -d'/' -f1 | rev | $MENU "wallpaper: ")
        if [ -z "$WALLPAPER" ]; then printf '%s\n' "No file selected" && notify-send "No file selected" && exit 2; fi
        swaybg --image "$(find "$WALLPAPERS_DIR" -type f | grep "$WALLPAPER")" &
        exit 0
}

### checking dependencies ###

for DEPENDENCY in swaybg
do
        if command -v "$DEPENDENCY" >/dev/null 2>&1; then true; else
                sendFeedback "Error: dependency not found: $DEPENDENCY" && exit 2; fi
done

for VARIABLE_NAME in WALLPAPERS_DIR GUI_MENU TERM_MENU
do
        eval VARIABLE="\$$VARIABLE_NAME"
        if [ -n "$VARIABLE" ]; then true; else
                sendFeedback "Error: variable undefined: $VARIABLE_NAME" && exit 3; fi
done

### dynamic menu ###

if [ -t 1 ]; then
        MENU="$TERM_MENU"
else
        MENU="$GUI_MENU"
fi

### options and commands ###

case $1 in
        random) randomWall;;
        select) selectWall;;
        *) printf '%s\n' "Error: Incorrect option" && exit 1;;
esac
