#!/bin/sh
#
# summary: a simple posix wrapper script for setting wallpapers
# repository: https://github.com/hollowillow/scripts
#
# usage: wp [arg]
# arguments: 
#
#       random  selects a random wallpaper
#       select  fuzzy search to select wallpaper
#       help    bring up this message
#
# dependencies: fzf, swaybg (wayland), fehbg (x11)

WALLPAPERS_DIR="${WALLPAPERS_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/wallpapers}"
mkdir -p "$WALLPAPERS_DIR" # create directory if it doesn't already exist
cd "$WALLPAPERS_DIR" || { printf '%s\n' "Error: $WALLPAPERS_DIR not found"; exit 2; }

printHelp() {
        # creates a help message from comment block at the top of the file
        sed "1,2d;s/^# //;s/^#$/ /;/^$/ q" "$0"; exit 0
}

setWallpaper() {
        if [ "$(printenv XDG_SESSION_TYPE)" = wayland ]; then
                pkill swaybg;
                setsid swaybg --image "$1" & disown
        elif [ "$(printenv XDG_SESSION_TYPE)" = x11 ]; then
                fehbg --no-fehbg --bg-scale "$1" & exit 0
        fi
}

randomWallpaper() {
        WALLPAPER="$(find . -type f -not -path '*/\.git/*' | shuf -n 1)"
        if [ -n "$WALLPAPER" ]; then 
                setWallpaper "$WALLPAPER";
                printf '%s\n' "Set random wallpaper.";
        else
                printf '%s\n' "No file selected."; exit 1
        fi
}

selectWallpaper() {
        SELECTED="$(\
                find . -type f -not -path '*/\.git/*' |
                fzf --prompt "wallpaper: " \
                        --preview="previewer {}"
        )"
        if [ -n "$SELECTED" ]; then 
                setWallpaper "$SELECTED";
                printf '%s\n' "Set selected wallpaper"; exit 0
        else
                sendFeedback "No file selected!"; exit 1
        fi
}

main() {
        case $1 in
                help|-h|--help) printHelp;;
                random) randomWallpaper;;
                select) selectWallpaper;;
        esac
}

main "$@"
