#!/bin/sh
#
# summary: a simple posix wrapper script for setting wallpapers on wayland
# repository: https://github.com/hollowillow/scripts
#
# usage: wp subcommand
# subcommands: 
#
#       random  selects a random wallpaper
#       select  fuzzy search to select wallpaper
#
# dependencies: rofi, fd, aww

. _lib # library script with common functions and variables
case "$1" in -h|-help|--help|help) printHelp ;; esac
checkDependency "rofi"

WALLPAPERS_DIR="${WALLPAPERS_DIR:-${XDG_PICTURES_DIR:-$HOME/Pictures}/wallpapers}"
mkdir -p "$WALLPAPERS_DIR" # create directory if it doesn't already exist
cd "$WALLPAPERS_DIR" 2>/dev/null || printErr \
    "wallpaper directory not found" \
    "run the script again to create it"

getPaths() {
    fd \
        --type f \
        --glob '*.{jpg,jpeg,png,webp,gif,bmp,avif}' \
        --absolute-path \
        . "$WALLPAPERS_DIR" 2>/dev/null
}

selectWallpaper() {
    while IFS= read -r IN; do
        REL_PATH=${IN#"$WALLPAPERS_DIR"/}
        printf '%s\000icon\037%s\n' "$REL_PATH" "$IN"
    done |
    rofi \
        -dmenu \
        -show-icons \
        -theme "$HOME/.config/rofi/themes/image.rasi"
}

setWallpaper() {
    read -r IN
    ([ "$XDG_SESSION_TYPE" = "wayland" ] && command -v awww >/dev/null 2>&1) || exit 1
    awww img \
        --resize=crop \
        --transition-type=grow \
        --transition-pos=top \
        --transition-step=5 \
        --transition-fps=144 \
        "$IN"
    ln -sf "$IN" "${WALLPAPERS_DIR}/current-wp"
}

main() {
    case "$1" in
        random) getPaths | shuf -n1 | setWallpaper;;
        select) getPaths | sort -u | selectWallpaper | xargs -I {} realpath {} | setWallpaper;;
        set) realpath "$2" | setWallpaper ;;
    esac
}

main "$@"
