#!/bin/sh
#
# summary: a simple posix wrapper script for setting wallpapers on wayland
# repository: https://github.com/hollowillow/scripts
#
# usage: wp arg
# arguments: 
#
#       random  selects a random wallpaper
#       select  fuzzy search to select wallpaper
#
# dependencies: fzf, fd (optional, faster), swaybg

# creates a help message from comment block at the head of file
printHelp() { sed "1,2d;s/^# //;s/^#$/ /;/^$/ q" "$0"; exit 0; }
{ [ "$1" = '-h' ] || [ "$1" = '--help' ]; } && printHelp

printErr() { printf "%s$(basename "$0"): Error: $1\n" >&2; exit 1; }
for CMD in fzf swaybg; do
        command -v "$CMD" >/dev/null || printErr "dependency not found: $CMD"
done

WALLPAPERS_DIR="${WALLPAPERS_DIR:-${XDG_PICTURES_DIR:-$HOME/Pictures}/wallpapers}"
mkdir -p "$WALLPAPERS_DIR" # create directory if it doesn't already exist
cd "$WALLPAPERS_DIR" || printErr "wallpaper directory not found"

if command -v fd >/dev/null 2>&1; then
        WALLPAPERS=$(fd --color=always --type=f . 2>/dev/null | sort -u)
else
        WALLPAPERS=$(find . -not -path '*/\.git/*' -type f -printf '%P\n' 2>/dev/null | sort -u)
fi

setWallpaper() {
        pkill swaybg
        nohup swaybg --mode fill --image "./$1" >/dev/null 2>&1 &
}

randomWallpaper() {
        SELECTED="$(printf '%s' "$WALLPAPERS" | sed -e 's/\x1b\[[0-9;]*m//g' | shuf -n 1)"
        [ -n "$SELECTED" ] && setWallpaper "$SELECTED" && printf '%s\n' "Wallpaper set to: $SELECTED"
        exit 0
}

selectWallpaper() {
        SELECTED="$(printf '%s' "$WALLPAPERS" | fzf --ansi --prompt "wallpaper: " --preview="previewer {}")"
        [ -n "$SELECTED" ] && setWallpaper "$SELECTED" && printf '%s\n' "Wallpaper set to: $SELECTED"
        exit 0
}

main() {
        case "$1" in
                random) randomWallpaper;;
                select) selectWallpaper;;
        esac
}

main "$*"
